### ISSUE TITLE
YCM can't jump to definition

### ISSUE THREAD

**Issue by ih4cku** [ih4cku/blog#33]
Errror message: `RuntimeError: Can't jump to definition`
- [ ] https://github.com/Valloric/YouCompleteMe/issues/758
- [ ] https://github.com/Valloric/YouCompleteMe/issues/755

**Comment by MaikoID** [comment]
Ycm has a option to get tags from the tagfile that has this info. Sadly exu-ctags doesn't get well with overloaded methods, but maybe ycm can get the info and improve.

**Comment by ret2libc** [comment]
News on this? It makes the `Goto` command almost useless because many times you arrive at some point where you can't go anywhere :(

**Comment by tianser** [comment]
@ih4cku @MaikoID @ret2libc the issue is ok ?
in my c++ project, cannot jump to definition；
RuntimeError: Can't jump to definition.
log：
142 2017-06-14 18:08:11,518 - INFO - Received command request
143 Traceback (most recent call last):
144 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
145 return route.call(**args)
146 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
147 rv = callback(*a, **ka)
148 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
149 return callback( *args, **kwargs )
150 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
151 body = callback( *args, **kwargs )
152 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 83, in RunCompleterCommand
153 request_data ) )
154 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 336, in OnUserCommand
155 return command( self, request_data, arguments[ 1: ] )
156 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 121, in 
157 self._GoToDefinition( request_data ) ),
158 File "/root/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 176, in _GoToDefinition
159 raise RuntimeError( 'Can't jump to definition.' )
160 RuntimeError: Can't jump to definition.

**Comment by presmihaylov** [comment]
So exu-ctags isn't cool, but is there a way to make `GoTo` work with `cscopetag` instead?

Currently, I am using cscope's `cs find s` for finding symbol definitions and YCM's `GoTo` for jumping to header files.

But I would be glad if I can consolidate both of these features with YCM's `GoTo`
